Repository TechAndCheck/tech-and-check-alerts, pull requests merged in 2020-03, with the labels that each got.

#339 Add build stages to travis
  .travis.yml
Labels: bug, devops

#331 Store scrape log data more efficiently
  src/server/migrations/20200225232115-refactor-scrape-logs-response-status.js
  src/server/models/ScrapeLog.js
  src/server/workers/scrapers/AbstractScraper.js
  src/server/workers/scrapers/constants.js
Labels: requires migration

#338 Retry unsuccessful CNN scrapes
  src/server/queues/cnnTranscriptListCrawlerQueue/cnnTranscriptListCrawlerJobProcessor.js
Labels: enhancement, scraper

#342 Add CNN deduplication to national newsletter
  src/server/newsletters/NationalNewsletter.js
Labels: enhancement

#344 Specify Node 12.x
  .travis.yml
  README.md
  package.json
Labels: devops

#345 Clean start scripts
  package.json
  yarn.lock
Labels: SHAME

#346 Fix Known Spearker scraper name
  src/server/workers/scrapers/GoogleSpreadsheetScraper.js
  src/server/workers/scrapers/__test__/GoogleSpreadsheetScraper.test.js
  src/server/workers/scrapers/__test__/__snapshots__/GoogleSpreadsheetScraper.test.js.snap
  src/server/workers/scrapers/__test__/data/spreadsheetMock.csv
Labels: bug
